#!/bin/bash

DATA_DIR="${HOME}/.local/share/nvimd/sockets"

mkdir -p "${DATA_DIR}"

CWD="$(pwd | cut -d "/" -f 4-)"
TTY="$(tty | cut -d "/" -f 4)"

SOCKET="${DATA_DIR}/${TTY//\//__}__${CWD//\//__}.pipe"

if [ -S "${SOCKET}" ]
then
  nvim --server "${SOCKET}" --remote $@
  nvim --server "${SOCKET}" --remote-ui
else
  nvim $@
fi
