#!/bin/bash

DATA_DIR="${HOME}/.local/share/nvimd/sockets"

mkdir -p "${DATA_DIR}"

CWD="$(pwd)"
TTY="$(tty)"

SOCKET="${DATA_DIR}/${TTY//\//__}__${CWD//\//__}.pipe"

if [ -S "${SOCKET}" ]
then
  exit 0
fi

cleanup() {
  rm ${SOCKET}
  exit 0
}

trap cleanup SIGHUP SIGINT SIGQUIT SIGABRT SIGTERM

while true
do
  nvim --listen "${SOCKET}" --headless > /dev/null 2>&1 0< /dev/null

  sleep 1
done
