#!/bin/bash

DATA_DIR="${HOME}/.local/share/nvimd/sockets"

mkdir -p "${DATA_DIR}"

CWD="$(pwd)"
TTY="$(tty)"

SOCKET="${DATA_DIR}/${TTY//\//__}__${CWD//\//__}.pipe"

if [ ! -S "${SOCKET}" ]
then
  nvimd-server "${SOCKET}" /dev/null 2>&1 0< /dev/null &
fi

nvim --server "${SOCKET}" --remote "${1}"
nvim --server "${SOCKET}" --remote-ui
